In [2]:
import numpy as np


## DataTypes and Attributes

In [31]:
#NumPy's main datatype is ndarray
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
import pandas as pd


In [19]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [7]:
df = pd.DataFrame(a3
                 )

ValueError: Must pass 2-d input. shape=(2, 3, 3)

## 2. Creating Arrays


In [3]:
sample_array = np.array([1,2,3])

In [5]:
sample_array.dtype

dtype('int64')

In [6]:
ones = np.ones((3,3), dtype=int)

In [7]:
ones


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
range_array = np.arange(0, 15, 1.7)
range_array

array([ 0. ,  1.7,  3.4,  5.1,  6.8,  8.5, 10.2, 11.9, 13.6])

In [12]:
random_array = np.random.randint(0,15, size=(4,6))
random_array

array([[ 6,  7, 12,  3,  6,  2],
       [ 9,  0,  5,  6,  0,  5],
       [ 2, 13,  9,  8,  8, 13],
       [ 9, 10,  3,  8,  6,  2]])

In [13]:
random_array.size

24

In [15]:
random_array_2 = np.random.random((5,3)) * 5
random_array_2

array([[1.60982562, 3.23320199, 0.68380219],
       [2.95889982, 4.3371806 , 0.66732928],
       [4.83487033, 0.05088148, 1.97559539],
       [1.76574362, 4.19324111, 0.38066347],
       [4.71765612, 4.2840991 , 0.02316192]])

## 3. Viewing arrays and matrices

array([0.02316192, 0.05088148, 0.38066347, 0.66732928, 0.68380219,
       1.60982562, 1.76574362, 1.97559539, 2.95889982, 3.23320199,
       4.19324111, 4.2840991 , 4.3371806 , 4.71765612, 4.83487033])

In [17]:
np.unique(random_array)

array([ 0,  2,  3,  5,  6,  7,  8,  9, 10, 12, 13])

In [20]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a4 = np.random.randint(10, size=(2,3,4,5))
a4

array([[[[5, 0, 7, 3, 4],
         [6, 0, 3, 3, 4],
         [5, 5, 5, 0, 1],
         [8, 5, 1, 4, 9]],

        [[5, 0, 5, 8, 7],
         [5, 8, 5, 5, 3],
         [0, 8, 7, 7, 0],
         [4, 6, 2, 8, 5]],

        [[9, 1, 0, 1, 6],
         [3, 8, 7, 9, 0],
         [6, 7, 0, 5, 6],
         [2, 3, 7, 2, 9]]],


       [[[1, 8, 1, 1, 6],
         [4, 6, 1, 7, 3],
         [2, 5, 5, 0, 1],
         [6, 3, 3, 8, 5]],

        [[8, 0, 6, 6, 2],
         [4, 3, 9, 9, 7],
         [8, 4, 9, 6, 7],
         [7, 1, 9, 9, 5]],

        [[0, 8, 1, 1, 0],
         [8, 9, 6, 3, 5],
         [8, 2, 8, 5, 1],
         [3, 9, 0, 7, 3]]]])

In [28]:
#Get the first 4 numbers of the innermost array
a4[:, :, :, :]

array([[[[5, 0, 7, 3, 4],
         [6, 0, 3, 3, 4],
         [5, 5, 5, 0, 1],
         [8, 5, 1, 4, 9]],

        [[5, 0, 5, 8, 7],
         [5, 8, 5, 5, 3],
         [0, 8, 7, 7, 0],
         [4, 6, 2, 8, 5]],

        [[9, 1, 0, 1, 6],
         [3, 8, 7, 9, 0],
         [6, 7, 0, 5, 6],
         [2, 3, 7, 2, 9]]],


       [[[1, 8, 1, 1, 6],
         [4, 6, 1, 7, 3],
         [2, 5, 5, 0, 1],
         [6, 3, 3, 8, 5]],

        [[8, 0, 6, 6, 2],
         [4, 3, 9, 9, 7],
         [8, 4, 9, 6, 7],
         [7, 1, 9, 9, 5]],

        [[0, 8, 1, 1, 0],
         [8, 9, 6, 3, 5],
         [8, 2, 8, 5, 1],
         [3, 9, 0, 7, 3]]]])

## 4. Manipulating and comparing arrays

## Arithmetic (ADDING ARRAYS)

In [30]:
ones


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [32]:
a1

array([1, 2, 3])

In [33]:
a1 + ones

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [34]:
a1 - ones

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [35]:
a1 - ones

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [37]:
a1 * a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 36],
        [13, 28, 45],
        [16, 34, 54]]])

In [38]:
a1

array([1, 2, 3])

In [39]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## Aggregation (performing the same operation on a number of things)

In [41]:
listy_list = [1,2,3]
listy_list

[1, 2, 3]

In [42]:
a1

array([1, 2, 3])

In [43]:
type(a1)

numpy.ndarray

In [44]:
type(listy_list)

list

## LIST VS ARRAY:
## List is used to collect items that usually consist of elements of multiple data types. 
## An array is also a vital component that collects several items of the same data type. 
## List cannot manage arithmetic operations. 
## Array can manage arithmetic operations.

In [45]:
np.sum(listy_list)

6

## USE python methods (`sum()`) on Python DT's use NumPy methods (`np.sum()`) on NumPy arrays

In [53]:
massive_array = np.random.random(1000)
massive_array.size

1000

In [54]:
%timeit sum(massive_array) #Python sum
%timeit np.sum(massive_array) #Numpy sum

99.4 µs ± 9.85 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
4.46 µs ± 327 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [55]:
# Standard deviation = a measure of how spread out a group of numbers are
np.std(massive_array)

0.28274830546348556

In [56]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(massive_array)

0.07994660424247255