In [2]:
import numpy as np


## DataTypes and Attributes

In [3]:
#NumPy's main datatype is ndarray
a1 = np.array([1,2,3])

In [4]:
a1

array([1, 2, 3])

In [5]:
import pandas as pd


In [6]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7,8,9]],
               [[10,11,12],
                [13,14,15],
                [16,17,18]]])

In [7]:
df = pd.DataFrame(a3
                 )

ValueError: Must pass 2-d input. shape=(2, 3, 3)

## 2. Creating Arrays


In [3]:
sample_array = np.array([1,2,3])

In [5]:
sample_array.dtype

dtype('int64')

In [6]:
ones = np.ones((3,3), dtype=int)

In [7]:
ones


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [11]:
range_array = np.arange(0, 15, 1.7)
range_array

array([ 0. ,  1.7,  3.4,  5.1,  6.8,  8.5, 10.2, 11.9, 13.6])

In [12]:
random_array = np.random.randint(0,15, size=(4,6))
random_array

array([[ 6,  7, 12,  3,  6,  2],
       [ 9,  0,  5,  6,  0,  5],
       [ 2, 13,  9,  8,  8, 13],
       [ 9, 10,  3,  8,  6,  2]])

In [13]:
random_array.size

24

In [15]:
random_array_2 = np.random.random((5,3)) * 5
random_array_2

array([[1.60982562, 3.23320199, 0.68380219],
       [2.95889982, 4.3371806 , 0.66732928],
       [4.83487033, 0.05088148, 1.97559539],
       [1.76574362, 4.19324111, 0.38066347],
       [4.71765612, 4.2840991 , 0.02316192]])